image: docker:stable  # Docker image for building

stages:
  - build
  - test
  - deploy  # Optional deployment stage

test:
  stage: test
  script:
    - go mod download
    - go test -v ./...

build:
  stage: build
  script:
    - docker build -t my-app:latest .  # Build Docker image

deploy:
  stage: deploy
  script:
    - docker login $CI_REGISTRY  # Login to container registry (if pushing)
    - docker push $CI_REGISTRY/my-app:latest  # Push image (if pushing)
